# Generated by Django 5.0.1 on 2024-01-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority_type', models.CharField(choices=[('H', 'high_priority'), ('M', 'medium_priority'), ('L', 'low_priority')], max_length=1)),
            ],
        ),
    ]
